####################### SETUP #######################
### Download books data - and stores in bookList.json
GET http://localhost:3000/downloadBooks

### SetupDB - wipes users, books collection and insersts data from userList.json and bookList.json
GET http://localhost:3000/setupDB

####################### USER #######################
GET http://localhost:3000/getAllUsers

### user BookDetails
GET http://localhost:3000/getUserBorrowedBooks/U1001
###
GET http://localhost:3000/getUserReservedBooks/U1001
###
GET http://localhost:3000/getUserBookDetails/U1001

####################### BOOK #######################
GET http://localhost:3000/getAllBooks

####################### ACTIONS #######################
### borrow book:  U1001 OL28267487M OL362702W
POST http://localhost:3000/borrowBook
content-type: application/json

{
    "userId": "U1001",
    "OLId": "OL362702W"
}

### return book
POST http://localhost:3000/returnBook
content-type: application/json

{
    "userId": "U1001",
    "OLId": "OL362702W"
}