### Download books data - and stores in bookList.json
GET http://localhost:3000/downloadBooks

### SetupDB - wipes users, books collection and insersts data from userList.json and bookList.json
GET http://localhost:3000/setupDB

### getAllBooks from books collection
GET http://localhost:3000/getAllBooks

### getAllUsers from users collection
GET http://localhost:3000/getAllUsers